# Site settings
author: Samantha Aleman
title: 
header-img: img/home-bg.png
email: samantha.aleman25@gmail.com
copyright_name: Samantha Aleman
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  saleman25

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
